use thiserror::Error as TError;

/// Errors generated from this library
#[derive(Debug, TError)]
pub enum Error {
    /// Verifiable secret sharing scheme errors
    #[error("Vsss error: {0}")]
    Vsss(vsss_rs::Error),
    #[error("Error: {0}")]
    General(String),
}

impl From<vsss_rs::Error> for Error {
    fn from(e: vsss_rs::Error) -> Self {
        Self::Vsss(e)
    }
}

impl<C: frost_core::Ciphersuite> From<frost_core::Error<C>> for Error {
    fn from(e: frost_core::Error<C>) -> Self {
        Error::General(e.to_string())
    }
}

/// Results generated by this library
pub type FrostResult<T> = anyhow::Result<T, Error>;
